module.exports = {
  content: ["./src/IMTS/Pages/**/*.cshtml", "./**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#380001",
        "on-primary": "#ffffff",
        "primary-container": "#5a0c08",
        "on-primary-container": "#e27264",
        "primary-fixed": "#ffdad5",
        "primary-fixed-dim": "#ffb4a9",
        "on-primary-fixed": "#410001",
        "on-primary-fixed-variant": "#802820",
        "secondary": "#875300",
        "on-secondary": "#ffffff",
        "secondary-container": "#fcaa3e",
        "on-secondary-container": "#6c4100",
        "secondary-fixed": "#ffddb9",
        "secondary-fixed-dim": "#ffb964",
        "on-secondary-fixed": "#2b1700",
        "on-secondary-fixed-variant": "#663e00",
        "tertiary": "#686000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b9ae43",
        "on-tertiary-container": "#464000",
        "tertiary-fixed": "#f2e574",
        "tertiary-fixed-dim": "#d5c95b",
        "on-tertiary-fixed": "#1f1c00",
        "on-tertiary-fixed-variant": "#4e4800",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface": "#fcf9f8",
        "on-surface": "#1c1b1b",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "surface-variant": "#e5e2e1",
        "on-surface-variant": "#56423f",
        "outline": "#89726e",
        "outline-variant": "#dcc0bc",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#ffb4a9",
        "surface-tint": "#9f3f35",
        "brand-gold": "#DD9024",
        "brand-maroon": "#5A0C08",
        "brand-cream": "#FEF7EF",
        "brand-soft-yellow": "#FFF27F"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        base: "8px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        margin: "32px",
        gutter: "24px"
      },
      fontFamily: {
        "title-lg": ["Public Sans"],
        "headline-lg": ["Public Sans"],
        "headline-md": ["Public Sans"],
        "body-lg": ["Public Sans"],
        "body-md": ["Public Sans"],
        "label-md": ["Public Sans"],
        "label-sm": ["Public Sans"],
        "display-lg": ["Public Sans"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }]
      }
    }
  }
}
